on: [push]
name: AzureARMSample

jobs:
  build-and-deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/actions/login@v1
      env:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
